services:
  postgres:
    image: postgres:16
    container_name: talkwdata_postgres
    env_file: ./orchestration/.env
    environment:
      POSTGRES_USER: ${DAGSTER_PG_USERNAME}
      POSTGRES_PASSWORD: ${DAGSTER_PG_PASSWORD}
      POSTGRES_DB: ${DAGSTER_PG_DB}
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DAGSTER_PG_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - talkwdata_network

  dagster_webserver:
    build:
      context: .
      dockerfile: Dockerfile.orchestration
    image: dagster_orchestration:latest
    container_name: talkwdata_dagster_webserver
    env_file: ./orchestration/.env
    entrypoint:
      - dagster-webserver
      - -h
      - "0.0.0.0"
      - -p
      - "3000"
      - -w
      - /opt/dagster/dagster_home/workspace.yaml
    environment:
      DAGSTER_PG_USERNAME: ${DAGSTER_PG_USERNAME}
      DAGSTER_PG_PASSWORD: ${DAGSTER_PG_PASSWORD}
      DAGSTER_PG_HOSTNAME: postgres
      DAGSTER_PG_DB: ${DAGSTER_PG_DB}
      DAGSTER_OVERALL_CONCURRENCY_LIMIT: ${DAGSTER_OVERALL_CONCURRENCY_LIMIT}
    volumes:
      - ./dagster.yaml:/opt/dagster/dagster_home/dagster.yaml
      - ./workspace.yaml:/opt/dagster/dagster_home/workspace.yaml
      - ./volumes/dagster_home:/opt/dagster/dagster_home
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - talkwdata_network

  dagster_daemon:
    build:
      context: .
      dockerfile: Dockerfile.orchestration
    image: dagster_orchestration:latest
    container_name: talkwdata_dagster_daemon
    env_file: ./orchestration/.env
    working_dir: /opt/dagster/dagster_home
    entrypoint:
      - dagster-daemon
      - run
    environment:
      DAGSTER_PG_USERNAME: ${DAGSTER_PG_USERNAME}
      DAGSTER_PG_PASSWORD: ${DAGSTER_PG_PASSWORD}
      DAGSTER_PG_HOSTNAME: postgres
      DAGSTER_PG_DB: ${DAGSTER_PG_DB}
      DAGSTER_OVERALL_CONCURRENCY_LIMIT: ${DAGSTER_OVERALL_CONCURRENCY_LIMIT}
    volumes:
      - ./dagster.yaml:/opt/dagster/dagster_home/dagster.yaml
      - ./workspace.yaml:/opt/dagster/dagster_home/workspace.yaml
      - ./volumes/dagster_home:/opt/dagster/dagster_home
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - talkwdata_network

  dagster_orchestration:
    build:
      context: .
      dockerfile: Dockerfile.orchestration
    image: dagster_orchestration:latest
    container_name: talkwdata_dagster_orchestration
    env_file: ./orchestration/.env
    entrypoint:
      - dagster
      - api
      - grpc
      - -h
      - "0.0.0.0"
      - -p
      - "4000"
      - -m
      - orchestration.definitions
    environment:
      DAGSTER_PG_USERNAME: ${DAGSTER_PG_USERNAME}
      DAGSTER_PG_PASSWORD: ${DAGSTER_PG_PASSWORD}
      DAGSTER_PG_HOSTNAME: postgres
      DAGSTER_PG_DB: ${DAGSTER_PG_DB}
    volumes:
      - ./volumes/dagster_home:/opt/dagster/dagster_home
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - talkwdata_network

  server:
    build:
      context: ./server
      dockerfile: ../Dockerfile.server
    container_name: talkwdata_server
    ports:
      - "8000:8000"
    networks:
      - talkwdata_network

  # open-webui:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.UI
  #   container_name: talkwdata_open_webui
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - WEBUI_NAME=Talking to Data
  #     - OLLAMA_BASE_URL=http://host.docker.internal:11434
  #   volumes:
  #     - ./volumes/open-webui:/app/backend/data
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   restart: unless-stopped
  #   networks:
  #     - talkwdata_network

networks:
  talkwdata_network:
    driver: bridge

volumes:
  postgres_data:
  dagster_home:
      